// Auto-generated from CSV data
const DASHBOARD_DATA = {
  "creatives": [
    {
      "id": 0,
      "name": "Дино (детская комната)",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 259,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.664,
        "like": 0.529,
        "clarity": 0.525,
        "relevance": 0.634,
        "uniqueness": 0.652,
        "brandRecognition": 0.447,
        "brandFit": 0.625,
        "brandAttitude": 0.556,
        "intent": 0.413,
        "brandRecall": 0.7931034483,
        "productRecall": 0.7567567568,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/59e4a9d013243194a2c7a6fb299d49e8/?p=mb43DJQBV9bxv1OFtYfBjA"
    },
    {
      "id": 1,
      "name": "Пушистый кот",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 269,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.658,
        "like": 0.509,
        "clarity": 0.532,
        "relevance": 0.606,
        "uniqueness": 0.613,
        "brandRecognition": 0.465,
        "brandFit": 0.598,
        "brandAttitude": 0.506,
        "intent": 0.353,
        "brandRecall": 0.7472118959,
        "productRecall": 0.7063197026,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/dacf60e83485092acbdbe4ba146db148/?p=qlq7sGgywmeQMvHhbExKeA"
    },
    {
      "id": 2,
      "name": "Хурма вяжет",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 260,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.731,
        "like": 0.585,
        "clarity": 0.554,
        "relevance": 0.719,
        "uniqueness": 0.677,
        "brandRecognition": 0.508,
        "brandFit": 0.712,
        "brandAttitude": 0.634,
        "intent": 0.404,
        "brandRecall": 0.7846153846,
        "productRecall": 0.6961538462,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/e2e916cf1bdcbf98b8b0ddf93a24ed48/?p=7i2b4FQO8XHm6e1ZVjWhsw"
    },
    {
      "id": 3,
      "name": "Мама",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "РК Гигачат",
      "campaign": "РК Гигачат",
      "base": 302,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.834,
        "like": 0.695,
        "clarity": 0.69,
        "relevance": 0.69,
        "uniqueness": 0.699,
        "brandRecognition": 0.357,
        "brandFit": 0.623,
        "brandAttitude": 0.599,
        "intent": 0.444,
        "brandRecall": 0.6904761905,
        "productRecall": 0.5537848606,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/dca6c03d5b6a605ea429b504acc3de65/?p=jlBjs4VhF4G3qYAIV5F4TQ"
    },
    {
      "id": 4,
      "name": "Суперсила",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "РК Гигачат",
      "campaign": "РК Гигачат",
      "base": 301,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.663,
        "like": 0.528,
        "clarity": 0.583,
        "relevance": 0.611,
        "uniqueness": 0.571,
        "brandRecognition": 0.365,
        "brandFit": 0.607,
        "brandAttitude": 0.498,
        "intent": 0.343,
        "brandRecall": 0.8412698413,
        "productRecall": 0.6666666667,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/b25cce71d98b9380058a5481c96ef663/?p=NzRx_amyX6dT1bduex6RUA"
    },
    {
      "id": 5,
      "name": "Гупи",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 300,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.724,
        "like": 0.568,
        "clarity": 0.602,
        "relevance": 0.769,
        "uniqueness": 0.61,
        "brandRecognition": 0.549,
        "brandFit": 0.738,
        "brandAttitude": 0.656,
        "intent": 0.485,
        "brandRecall": 0.8977272727,
        "productRecall": 0.7878787879,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/476ed65bb0c669bdca427aac113182e9/?p=flR2eOpLlidsD8jLKzB5JA"
    },
    {
      "id": 6,
      "name": "Диета",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 304,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.656,
        "like": 0.519,
        "clarity": 0.553,
        "relevance": 0.607,
        "uniqueness": 0.572,
        "brandRecognition": 0.466,
        "brandFit": 0.606,
        "brandAttitude": 0.527,
        "intent": 0.371,
        "brandRecall": 0.7689393939,
        "productRecall": 0.6515151515,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/ad1c6ac0bde77eddcc92f347c0ee2e4b/?p=9xd7nb7MjpLwKHTs-MOsEw"
    },
    {
      "id": 7,
      "name": "Кот",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 303,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.751,
        "like": 0.609,
        "clarity": 0.648,
        "relevance": 0.667,
        "uniqueness": 0.625,
        "brandRecognition": 0.509,
        "brandFit": 0.666,
        "brandAttitude": 0.587,
        "intent": 0.429,
        "brandRecall": 0.8275862069,
        "productRecall": 0.7394636015,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/e5ad3da810893c61aadbe7427d4a7f99/?p=PNE1bwddjsBL6kShUazxRw"
    },
    {
      "id": 8,
      "name": "Поиск",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 301,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.779,
        "like": 0.599,
        "clarity": 0.641,
        "relevance": 0.748,
        "uniqueness": 0.618,
        "brandRecognition": 0.561,
        "brandFit": 0.729,
        "brandAttitude": 0.649,
        "intent": 0.454,
        "brandRecall": 0.9236641221,
        "productRecall": 0.8396946565,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/68cd6d2b09ba3d3b8f6ed1a50238e383/?p=eEVbPmAQ6SXhZoGOu2nXNg"
    },
    {
      "id": 9,
      "name": "Часы для бега",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "Поиск с Нейро",
      "campaign": "Нейро реально помогает",
      "base": 300,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.735,
        "like": 0.563,
        "clarity": 0.609,
        "relevance": 0.744,
        "uniqueness": 0.652,
        "brandRecognition": 0.548,
        "brandFit": 0.731,
        "brandAttitude": 0.655,
        "intent": 0.452,
        "brandRecall": 0.8735632184,
        "productRecall": 0.785440613,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/66398fdfd4214b2a3d73a0bd50da16b2/?p=aUsKlkz4zsknZ-KRxmSAAg"
    },
    {
      "id": 10,
      "name": "Помощь с креативом",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "РК Гигачат",
      "campaign": "РК Гигачат",
      "base": 305,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.669,
        "like": 0.508,
        "clarity": 0.573,
        "relevance": 0.553,
        "uniqueness": 0.605,
        "brandRecognition": 0.339,
        "brandFit": 0.577,
        "brandAttitude": 0.521,
        "intent": 0.371,
        "brandRecall": 0.6774193548,
        "productRecall": 0.564516129,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/315b6643e5a0fde45130768a4ab388b0/?p=AjTSwPFlAWZUaExiXWG8pQ"
    },
    {
      "id": 11,
      "name": "Занять ребенка",
      "task": "MR-3900",
      "period": "фев.25",
      "product": "РК Гигачат",
      "campaign": "РК Гигачат",
      "base": 296,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.699,
        "like": 0.541,
        "clarity": 0.602,
        "relevance": 0.593,
        "uniqueness": 0.626,
        "brandRecognition": 0.305,
        "brandFit": 0.578,
        "brandAttitude": 0.549,
        "intent": 0.378,
        "brandRecall": 0.6585365854,
        "productRecall": 0.6422764228,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/8386676aeef523c2ec1bfb4431908cfe/?p=QrKjoQbR8OSZPQqICb0uIQ"
    },
    {
      "id": 12,
      "name": "Все магазины, все товары. В Яндексе.",
      "task": "MR-2075",
      "period": "янв.21",
      "product": "Яндекс.Поиск",
      "campaign": "Яндекс.Поиск",
      "base": 200,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.65,
        "like": 0.47,
        "clarity": null,
        "relevance": 0.63,
        "uniqueness": 0.5,
        "brandRecognition": null,
        "brandFit": null,
        "brandAttitude": null,
        "intent": 0.61,
        "brandRecall": null,
        "productRecall": null,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://youtu.be/OaSS_7fiNjo"
    },
    {
      "id": 13,
      "name": "Где выбрать кроссовки по картинкам. Там, где найдется все. В Яндексе.",
      "task": "MR-2075",
      "period": "янв.21",
      "product": "Яндекс.Поиск",
      "campaign": "Яндекс.Поиск",
      "base": 181,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.73,
        "like": 0.55,
        "clarity": null,
        "relevance": 0.66,
        "uniqueness": 0.58,
        "brandRecognition": null,
        "brandFit": null,
        "brandAttitude": null,
        "intent": 0.66,
        "brandRecall": null,
        "productRecall": null,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://youtu.be/wa8LD13ZH_Q"
    },
    {
      "id": 14,
      "name": "Человек-паук",
      "task": "MR-3462",
      "period": "фев.24",
      "product": "Я.Бро",
      "campaign": "РК \"Нейробраузер\"",
      "base": 538,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7472118959,
        "like": 0.5650557621,
        "clarity": 0.592936803,
        "relevance": 0.6542750929,
        "uniqueness": 0.6226765799,
        "brandRecognition": 0.4814126394,
        "brandFit": 0.7137546468,
        "brandAttitude": 0.6078066914,
        "intent": 0.4330855019,
        "brandRecall": 0.8494423792,
        "productRecall": 0.6468401487,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 15,
      "name": "Дедпул",
      "task": "MR-3462",
      "period": "фев.24",
      "product": "Я.Бро",
      "campaign": "РК \"Нейробраузер\"",
      "base": 532,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7086466165,
        "like": 0.5620300752,
        "clarity": 0.5488721805,
        "relevance": 0.6127819549,
        "uniqueness": 0.6184210526,
        "brandRecognition": 0.469924812,
        "brandFit": 0.6616541353,
        "brandAttitude": 0.5620300752,
        "intent": 0.3928571429,
        "brandRecall": 0.8552631579,
        "productRecall": 0.6484962406,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 16,
      "name": "Сплит",
      "task": "MR-3764",
      "period": "окт.24",
      "product": "Я.Бро",
      "campaign": "РК \"ЕКОМ\"",
      "base": 434,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7004608295,
        "like": 0.5460829493,
        "clarity": 0.6451612903,
        "relevance": 0.5529953917,
        "uniqueness": 0.5529953917,
        "brandRecognition": 0.4631336406,
        "brandFit": 0.6428571429,
        "brandAttitude": 0.4953917051,
        "intent": 0.2995391705,
        "brandRecall": 0.82,
        "productRecall": 0.72,
        "correctFeatures": 0.6889400922,
        "incorrectFeatures": 0.1451612903
      },
      "rutubeUrl": null
    },
    {
      "id": 17,
      "name": "Кешбек",
      "task": "MR-3764",
      "period": "окт.24",
      "product": "Я.Бро",
      "campaign": "РК \"ЕКОМ\"",
      "base": 428,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7663551402,
        "like": 0.6378504673,
        "clarity": 0.6074766355,
        "relevance": 0.6682242991,
        "uniqueness": 0.6308411215,
        "brandRecognition": 0.441588785,
        "brandFit": 0.6682242991,
        "brandAttitude": 0.5630841121,
        "intent": 0.3714953271,
        "brandRecall": 0.79,
        "productRecall": 0.48,
        "correctFeatures": 0.4369158879,
        "incorrectFeatures": 0.3014018692
      },
      "rutubeUrl": null
    },
    {
      "id": 18,
      "name": "Промокоды",
      "task": "MR-3764",
      "period": "окт.24",
      "product": "Я.Бро",
      "campaign": "РК \"ЕКОМ\"",
      "base": 438,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.703196347,
        "like": 0.5091324201,
        "clarity": 0.5730593607,
        "relevance": 0.6073059361,
        "uniqueness": 0.5456621005,
        "brandRecognition": 0.4337899543,
        "brandFit": 0.6301369863,
        "brandAttitude": 0.502283105,
        "intent": 0.3310502283,
        "brandRecall": 0.87,
        "productRecall": 0.51,
        "correctFeatures": 0.3744292237,
        "incorrectFeatures": 0.3424657534
      },
      "rutubeUrl": null
    },
    {
      "id": 19,
      "name": "1 На коне Нейроредактор",
      "task": "MR-4009",
      "period": "май.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 414,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.71,
        "like": 0.56,
        "clarity": 0.61,
        "relevance": 0.57,
        "uniqueness": 0.61,
        "brandRecognition": 0.5,
        "brandFit": 0.68,
        "brandAttitude": 0.52,
        "intent": 0.38,
        "brandRecall": 0.85,
        "productRecall": 0.72,
        "correctFeatures": 0.52,
        "incorrectFeatures": 0.3
      },
      "rutubeUrl": "https://rutube.ru/video/private/d44e98dda41778a8cbab9085b0c467ed/?p=5UtweU61JEFwG2XLwVqdfg"
    },
    {
      "id": 20,
      "name": "2 Облако Перевод видео",
      "task": "MR-4009",
      "period": "май.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 435,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.74,
        "like": 0.59,
        "clarity": 0.65,
        "relevance": 0.69,
        "uniqueness": 0.66,
        "brandRecognition": 0.52,
        "brandFit": 0.73,
        "brandAttitude": 0.61,
        "intent": 0.44,
        "brandRecall": 0.8,
        "productRecall": 0.63,
        "correctFeatures": 0.74,
        "incorrectFeatures": 0.1
      },
      "rutubeUrl": "https://rutube.ru/video/private/c2e060a3b1fcc684302615dc6d21bdcd/?p=HfuGyXS0vtpEZeCv_4_4rQ"
    },
    {
      "id": 21,
      "name": "3.1 На волне (пересказ видео)_10 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 424,
      "format": "10 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.6,
        "like": 0.42,
        "clarity": 0.47,
        "relevance": 0.53,
        "uniqueness": 0.51,
        "brandRecognition": 0.45,
        "brandFit": 0.59,
        "brandAttitude": 0.46,
        "intent": 0.34,
        "brandRecall": 0.81,
        "productRecall": 0.49,
        "correctFeatures": 0.36,
        "incorrectFeatures": 0.25
      },
      "rutubeUrl": null
    },
    {
      "id": 22,
      "name": "3.2 На волне (пересказ видео)_25 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 412,
      "format": "25 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.69,
        "like": 0.52,
        "clarity": 0.59,
        "relevance": 0.59,
        "uniqueness": 0.54,
        "brandRecognition": 0.5,
        "brandFit": 0.67,
        "brandAttitude": 0.49,
        "intent": 0.38,
        "brandRecall": 0.83,
        "productRecall": 0.63,
        "correctFeatures": 0.43,
        "incorrectFeatures": 0.28
      },
      "rutubeUrl": null
    },
    {
      "id": 23,
      "name": "4.1 По нотам (поиск с Алисой)_10 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 408,
      "format": "10 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.57,
        "like": 0.4,
        "clarity": 0.57,
        "relevance": 0.55,
        "uniqueness": 0.47,
        "brandRecognition": 0.43,
        "brandFit": 0.6,
        "brandAttitude": 0.4,
        "intent": 0.29,
        "brandRecall": 0.86,
        "productRecall": 0.68,
        "correctFeatures": 0.37,
        "incorrectFeatures": 0.29
      },
      "rutubeUrl": null
    },
    {
      "id": 24,
      "name": "4.2 По нотам (поиск с Алисой)_25 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 418,
      "format": "25 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.71,
        "like": 0.54,
        "clarity": 0.61,
        "relevance": 0.6,
        "uniqueness": 0.6,
        "brandRecognition": 0.5,
        "brandFit": 0.69,
        "brandAttitude": 0.5,
        "intent": 0.37,
        "brandRecall": 0.86,
        "productRecall": 0.72,
        "correctFeatures": 0.43,
        "incorrectFeatures": 0.26
      },
      "rutubeUrl": null
    },
    {
      "id": 25,
      "name": "5.1 Гора (Протект)_10 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 409,
      "format": "10 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.63,
        "like": 0.48,
        "clarity": 0.52,
        "relevance": 0.62,
        "uniqueness": 0.51,
        "brandRecognition": 0.42,
        "brandFit": 0.59,
        "brandAttitude": 0.48,
        "intent": 0.33,
        "brandRecall": 0.82,
        "productRecall": 0.7,
        "correctFeatures": 0.5,
        "incorrectFeatures": 0.26
      },
      "rutubeUrl": null
    },
    {
      "id": 26,
      "name": "5.2 Гора (Протект)_25 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 411,
      "format": "25 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.73,
        "like": 0.58,
        "clarity": 0.62,
        "relevance": 0.66,
        "uniqueness": 0.63,
        "brandRecognition": 0.43,
        "brandFit": 0.66,
        "brandAttitude": 0.57,
        "intent": 0.36,
        "brandRecall": 0.84,
        "productRecall": 0.77,
        "correctFeatures": 0.54,
        "incorrectFeatures": 0.32
      },
      "rutubeUrl": null
    },
    {
      "id": 27,
      "name": "6.1 Штаны (кешбэк)_10 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 399,
      "format": "10 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.67,
        "like": 0.47,
        "clarity": 0.55,
        "relevance": 0.57,
        "uniqueness": 0.55,
        "brandRecognition": 0.42,
        "brandFit": 0.64,
        "brandAttitude": 0.45,
        "intent": 0.29,
        "brandRecall": 0.84,
        "productRecall": 0.66,
        "correctFeatures": 0.53,
        "incorrectFeatures": 0.2
      },
      "rutubeUrl": null
    },
    {
      "id": 28,
      "name": "6.2 Штаны (Кешбэк)_25 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 405,
      "format": "25 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.67,
        "like": 0.51,
        "clarity": 0.6,
        "relevance": 0.57,
        "uniqueness": 0.55,
        "brandRecognition": 0.45,
        "brandFit": 0.61,
        "brandAttitude": 0.49,
        "intent": 0.32,
        "brandRecall": 0.77,
        "productRecall": 0.61,
        "correctFeatures": 0.56,
        "incorrectFeatures": 0.25
      },
      "rutubeUrl": null
    },
    {
      "id": 29,
      "name": "7.1 Крылья (Промокоды)_10 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 431,
      "format": "10 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.68,
        "like": 0.52,
        "clarity": 0.64,
        "relevance": 0.67,
        "uniqueness": 0.57,
        "brandRecognition": 0.51,
        "brandFit": 0.71,
        "brandAttitude": 0.51,
        "intent": 0.37,
        "brandRecall": 0.88,
        "productRecall": 0.68,
        "correctFeatures": 0.59,
        "incorrectFeatures": 0.07
      },
      "rutubeUrl": null
    },
    {
      "id": 30,
      "name": "7.2 Крылья (Промокоды)_25 сек",
      "task": "MR-4044",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 420,
      "format": "25 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.68,
        "like": 0.53,
        "clarity": 0.63,
        "relevance": 0.65,
        "uniqueness": 0.53,
        "brandRecognition": 0.46,
        "brandFit": 0.68,
        "brandAttitude": 0.52,
        "intent": 0.38,
        "brandRecall": 0.81,
        "productRecall": 0.56,
        "correctFeatures": 0.61,
        "incorrectFeatures": 0.2
      },
      "rutubeUrl": null
    },
    {
      "id": 31,
      "name": "Яндекс с Алисой (ИИ реально помогает)",
      "task": "MR-4042",
      "period": "май.25",
      "product": "Поиск с Алисой",
      "campaign": "Яндекс с Алисой",
      "base": 252,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.8,
        "like": 0.64,
        "clarity": 0.65,
        "relevance": 0.78,
        "uniqueness": 0.66,
        "brandRecognition": 0.64,
        "brandFit": 0.8,
        "brandAttitude": 0.63,
        "intent": 0.44,
        "brandRecall": 0.92,
        "productRecall": 0.83,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/0edf4aa400fb72ae7f4100230a6f3f31/?p=h_3Kagq0qzlGqx6JitxAgQ"
    },
    {
      "id": 32,
      "name": "Облако Продакшн",
      "task": "MR-4081",
      "period": "июн.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 406,
      "format": "Ролик",
      "productionType": "Продакшн",
      "metrics": {
        "interesting": 0.74,
        "like": 0.57,
        "clarity": 0.86,
        "relevance": 0.66,
        "uniqueness": 0.63,
        "brandRecognition": 0.5,
        "brandFit": 0.71,
        "brandAttitude": 0.6,
        "intent": 0.43,
        "brandRecall": null,
        "productRecall": null,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 33,
      "name": "Облако ИИ",
      "task": "MR-4081",
      "period": "июл.25",
      "product": "Я.Бро",
      "campaign": "РК \"Нейропродуктивность\" (Always on)",
      "base": 431,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.76,
        "like": 0.66,
        "clarity": 0.89,
        "relevance": 0.67,
        "uniqueness": 0.64,
        "brandRecognition": 0.51,
        "brandFit": 0.74,
        "brandAttitude": 0.59,
        "intent": 0.47,
        "brandRecall": null,
        "productRecall": null,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/0bded83101d4e5a42e567ede925655e9/?r=wd"
    },
    {
      "id": 34,
      "name": "YB_Original_Perevod",
      "task": "MR-4081",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 425,
      "format": "Ролик",
      "productionType": "Продакшн",
      "metrics": {
        "interesting": 0.76,
        "like": 0.6,
        "clarity": 0.69,
        "relevance": 0.69,
        "uniqueness": 0.68,
        "brandRecognition": 0.52,
        "brandFit": 0.72,
        "brandAttitude": 0.65,
        "intent": 0.47,
        "brandRecall": 0.22,
        "productRecall": 0.33,
        "correctFeatures": 0.74,
        "incorrectFeatures": 0.13
      },
      "rutubeUrl": "https://rutube.ru/video/private/5f7527fb9352708e7911fd6e3f1b26f5/?r=wd"
    },
    {
      "id": 35,
      "name": "YB_AI_Cringe",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 513,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.79,
        "like": 0.63,
        "clarity": 0.71,
        "relevance": 0.66,
        "uniqueness": 0.73,
        "brandRecognition": 0.52,
        "brandFit": 0.77,
        "brandAttitude": 0.6,
        "intent": 0.41,
        "brandRecall": 0.28,
        "productRecall": 0.32,
        "correctFeatures": 0.78,
        "incorrectFeatures": 0.09
      },
      "rutubeUrl": "https://rutube.ru/video/private/153c2851c211a607442d966f49ba0098/?r=wd"
    },
    {
      "id": 36,
      "name": "YB_AI_Pixar_Bus_Perevod",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 417,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.72,
        "like": 0.56,
        "clarity": 0.65,
        "relevance": 0.69,
        "uniqueness": 0.68,
        "brandRecognition": 0.47,
        "brandFit": 0.7,
        "brandAttitude": 0.57,
        "intent": 0.4,
        "brandRecall": 0.21,
        "productRecall": 0.33,
        "correctFeatures": 0.72,
        "incorrectFeatures": 0.1
      },
      "rutubeUrl": "https://rutube.ru/video/private/e18e5ab20b6263aa55addd8a0d57203d/?r=wd"
    },
    {
      "id": 37,
      "name": "YB_Ambi_AI_Bus_Perevod",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 413,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.74,
        "like": 0.6,
        "clarity": 0.73,
        "relevance": 0.69,
        "uniqueness": 0.69,
        "brandRecognition": 0.51,
        "brandFit": 0.74,
        "brandAttitude": 0.6,
        "intent": 0.44,
        "brandRecall": 0.21,
        "productRecall": 0.35,
        "correctFeatures": 0.72,
        "incorrectFeatures": 0.09
      },
      "rutubeUrl": "https://rutube.ru/video/private/2eca7302da5f81db6c192ddc79b57e01/?r=wd"
    },
    {
      "id": 38,
      "name": "7 YB_AI_Vasya_Perevod",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 410,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.77,
        "like": 0.65,
        "clarity": 0.69,
        "relevance": 0.71,
        "uniqueness": 0.71,
        "brandRecognition": 0.52,
        "brandFit": 0.77,
        "brandAttitude": 0.64,
        "intent": 0.46,
        "brandRecall": 0.27,
        "productRecall": 0.3,
        "correctFeatures": 0.73,
        "incorrectFeatures": 0.1
      },
      "rutubeUrl": "https://rutube.ru/video/private/837f37ed7a907f3c74a54cad07fb158c/?r=wd"
    },
    {
      "id": 39,
      "name": "5 Я.Бро (Пересказ, Оригинал)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 424,
      "format": "Ролик",
      "productionType": "Продакшн",
      "metrics": {
        "interesting": 0.75,
        "like": 0.58,
        "clarity": 0.63,
        "relevance": 0.66,
        "uniqueness": 0.64,
        "brandRecognition": 0.57,
        "brandFit": 0.73,
        "brandAttitude": 0.6,
        "intent": 0.43,
        "brandRecall": 0.2,
        "productRecall": 0.28,
        "correctFeatures": 0.51,
        "incorrectFeatures": 0.26
      },
      "rutubeUrl": "https://rutube.ru/video/private/0fee2b044a2afcc85907370ce2bbc4a2/?r=wd"
    },
    {
      "id": 40,
      "name": "4 Я.Бро (Пересказ, ИИ)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Я.Бро",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 403,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.72,
        "like": 0.58,
        "clarity": 0.61,
        "relevance": 0.66,
        "uniqueness": 0.61,
        "brandRecognition": 0.53,
        "brandFit": 0.72,
        "brandAttitude": 0.55,
        "intent": 0.39,
        "brandRecall": 0.16,
        "productRecall": 0.23,
        "correctFeatures": 0.44,
        "incorrectFeatures": 0.28
      },
      "rutubeUrl": "https://rutube.ru/video/private/8a2cf058087809451bf250026db5ef32/?r=wd"
    },
    {
      "id": 41,
      "name": "ВБ (Черная Пятница и Харламов)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "ВБ",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 448,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.74,
        "like": 0.56,
        "clarity": 0.73,
        "relevance": 0.74,
        "uniqueness": 0.56,
        "brandRecognition": 0.54,
        "brandFit": 0.75,
        "brandAttitude": 0.45,
        "intent": 0.39,
        "brandRecall": 0.72,
        "productRecall": 0.58,
        "correctFeatures": 0.66,
        "incorrectFeatures": 0.07
      },
      "rutubeUrl": "https://rutube.ru/video/private/551c1433728b5e0d2e018fc15ab002ea/?r=wd"
    },
    {
      "id": 42,
      "name": "ГигаЧат1  (письмо простыми словами)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "ГигаЧат",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 410,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7,
        "like": 0.54,
        "clarity": 0.58,
        "relevance": 0.6,
        "uniqueness": 0.6,
        "brandRecognition": 0.38,
        "brandFit": 0.6,
        "brandAttitude": 0.55,
        "intent": 0.38,
        "brandRecall": 0.36,
        "productRecall": 0.29,
        "correctFeatures": 0.29,
        "incorrectFeatures": 0.11
      },
      "rutubeUrl": "https://rutube.ru/video/private/c48cde587aa166e23d6169c9b1222186/?r=wd"
    },
    {
      "id": 43,
      "name": "1ГигаЧат(помощь с юр.доками)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "ГигаЧат",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 417,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.68,
        "like": 0.49,
        "clarity": 0.55,
        "relevance": 0.57,
        "uniqueness": 0.57,
        "brandRecognition": 0.38,
        "brandFit": 0.59,
        "brandAttitude": 0.52,
        "intent": 0.31,
        "brandRecall": 0.39,
        "productRecall": 0.48,
        "correctFeatures": 0.51,
        "incorrectFeatures": 0.14
      },
      "rutubeUrl": "https://rutube.ru/video/private/61311b769554a89f33b158f362e67f09/?r=wd"
    },
    {
      "id": 44,
      "name": "Островок (отсылка к белому лотосу)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Островок",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 455,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.62,
        "like": 0.45,
        "clarity": 0.51,
        "relevance": 0.5,
        "uniqueness": 0.54,
        "brandRecognition": 0.33,
        "brandFit": 0.49,
        "brandAttitude": 0.4,
        "intent": 0.27,
        "brandRecall": 0.81,
        "productRecall": 0.25,
        "correctFeatures": 0.56,
        "incorrectFeatures": 0.15
      },
      "rutubeUrl": "https://rutube.ru/video/private/55ed0dba4ad21eaae8d2e9b10829a596/?r=wd"
    },
    {
      "id": 45,
      "name": "Авиасэйлс (Сочи)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Авиасэйлс",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 398,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.68,
        "like": 0.54,
        "clarity": 0.68,
        "relevance": 0.56,
        "uniqueness": 0.65,
        "brandRecognition": 0.47,
        "brandFit": 0.61,
        "brandAttitude": 0.48,
        "intent": 0.36,
        "brandRecall": 0.76,
        "productRecall": 0.31,
        "correctFeatures": 0.66,
        "incorrectFeatures": 0.47
      },
      "rutubeUrl": "https://rutube.ru/video/private/55ed0dba4ad21eaae8d2e9b10829a596/?r=wd"
    },
    {
      "id": 46,
      "name": "Суточно.ру (Квартиру сниму на Суточно.ру)",
      "task": "MR-4085",
      "period": "авг.25",
      "product": "Суточно.ру",
      "campaign": "Кринж+ИИ VS продакшн",
      "base": 425,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.64,
        "like": 0.51,
        "clarity": 0.71,
        "relevance": 0.55,
        "uniqueness": 0.56,
        "brandRecognition": 0.49,
        "brandFit": 0.67,
        "brandAttitude": 0.51,
        "intent": 0.35,
        "brandRecall": 0.84,
        "productRecall": 0.21,
        "correctFeatures": 0.76,
        "incorrectFeatures": 0.12
      },
      "rutubeUrl": "https://rutube.ru/video/c48cde587aa166e23d6169c9b1222186/?utm_source=embed&utm_medium=referral&utm_campaign=main_logo&utm_content=c48cde587aa166e23d6169c9b1222186&utm_term=surveys.yandex.ru&t=0&p=tYz7U0VypQi9zWwfJ6Nrhw"
    },
    {
      "id": 47,
      "name": "Ленивец вклад",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Выгодный Вклад",
      "base": 244,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.6,
        "clarity": 0.63,
        "relevance": 0.77,
        "uniqueness": 0.66,
        "brandRecognition": 0.46,
        "brandFit": 0.71,
        "brandAttitude": 0.59,
        "intent": 0.37,
        "brandRecall": 0.84,
        "productRecall": 0.56,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 48,
      "name": "Ленивец вклад+строка",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Выгодный Вклад",
      "base": 224,
      "format": "Ролик + строка",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.73,
        "like": 0.54,
        "clarity": 0.61,
        "relevance": 0.76,
        "uniqueness": 0.61,
        "brandRecognition": 0.42,
        "brandFit": 0.71,
        "brandAttitude": 0.56,
        "intent": 0.33,
        "brandRecall": 0.89,
        "productRecall": 0.62,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 49,
      "name": "Кролик вклад",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Выгодный Вклад",
      "base": 221,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.7,
        "like": 0.55,
        "clarity": 0.62,
        "relevance": 0.68,
        "uniqueness": 0.6,
        "brandRecognition": 0.46,
        "brandFit": 0.72,
        "brandAttitude": 0.55,
        "intent": 0.39,
        "brandRecall": 0.88,
        "productRecall": 0.51,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 50,
      "name": "Кролик вклад+строка",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Выгодный Вклад",
      "base": 248,
      "format": "Ролик + строка",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.68,
        "like": 0.52,
        "clarity": 0.6,
        "relevance": 0.75,
        "uniqueness": 0.58,
        "brandRecognition": 0.52,
        "brandFit": 0.71,
        "brandAttitude": 0.52,
        "intent": 0.38,
        "brandRecall": 0.92,
        "productRecall": 0.54,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 51,
      "name": "Банки.ру вклад",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Вклад",
      "base": 275,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.72,
        "like": 0.55,
        "clarity": 0.63,
        "relevance": 0.72,
        "uniqueness": 0.53,
        "brandRecognition": 0.39,
        "brandFit": 0.73,
        "brandAttitude": 0.52,
        "intent": 0.29,
        "brandRecall": 0.87,
        "productRecall": 0.37,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 52,
      "name": "Сравни вклад",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "Вклад",
      "base": 257,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.61,
        "clarity": 0.71,
        "relevance": 0.8,
        "uniqueness": 0.62,
        "brandRecognition": 0.51,
        "brandFit": 0.74,
        "brandAttitude": 0.65,
        "intent": 0.38,
        "brandRecall": 0.82,
        "productRecall": 0.61,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 53,
      "name": "Ленивец-строка",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "ОСАГО",
      "base": 310,
      "format": "Ролик + строка",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.63,
        "clarity": 0.68,
        "relevance": 0.83,
        "uniqueness": 0.66,
        "brandRecognition": 0.57,
        "brandFit": 0.73,
        "brandAttitude": 0.58,
        "intent": 0.43,
        "brandRecall": 0.8,
        "productRecall": 0.76,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 54,
      "name": "Ленивец",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "ОСАГО",
      "base": 303,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.8,
        "like": 0.64,
        "clarity": 0.67,
        "relevance": 0.87,
        "uniqueness": 0.7,
        "brandRecognition": 0.57,
        "brandFit": 0.78,
        "brandAttitude": 0.65,
        "intent": 0.45,
        "brandRecall": 0.77,
        "productRecall": 0.74,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 55,
      "name": "Банки",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "ОСАГО",
      "base": 304,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.69,
        "like": 0.6,
        "clarity": 0.66,
        "relevance": 0.79,
        "uniqueness": 0.6,
        "brandRecognition": 0.48,
        "brandFit": 0.73,
        "brandAttitude": 0.59,
        "intent": 0.35,
        "brandRecall": 0.82,
        "productRecall": 0.82,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 56,
      "name": "Банки 4000",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "ОСАГО",
      "base": 310,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.75,
        "like": 0.59,
        "clarity": 0.71,
        "relevance": 0.8,
        "uniqueness": 0.64,
        "brandRecognition": 0.53,
        "brandFit": 0.75,
        "brandAttitude": 0.64,
        "intent": 0.36,
        "brandRecall": 0.8,
        "productRecall": 0.92,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 57,
      "name": "Сравни",
      "task": "MR-4111",
      "period": "окт.25",
      "product": "Финансы",
      "campaign": "ОСАГО",
      "base": 282,
      "format": "Ролик",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.62,
        "clarity": 0.72,
        "relevance": 0.85,
        "uniqueness": 0.66,
        "brandRecognition": 0.58,
        "brandFit": 0.78,
        "brandAttitude": 0.64,
        "intent": 0.44,
        "brandRecall": 0.72,
        "productRecall": 0.9,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": null
    },
    {
      "id": 58,
      "name": "Алиса 30 сек",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Алиса AI",
      "campaign": "Запуск 28.10",
      "base": 225,
      "format": "30 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.59,
        "clarity": 0.65,
        "relevance": 0.68,
        "uniqueness": 0.61,
        "brandRecognition": 0.46,
        "brandFit": 0.75,
        "brandAttitude": 0.62,
        "intent": 0.44,
        "brandRecall": 0.6,
        "productRecall": 0.64,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/09871b274791d0ebe954c8a457f10a4c/?p=hVW8_9EJLLpEtYhsyCQoAg"
    },
    {
      "id": 59,
      "name": "Алиса 15 сек",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Алиса AI",
      "campaign": "Запуск 28.10",
      "base": 231,
      "format": "15 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.71,
        "like": 0.55,
        "clarity": 0.61,
        "relevance": 0.66,
        "uniqueness": 0.6,
        "brandRecognition": 0.47,
        "brandFit": 0.73,
        "brandAttitude": 0.55,
        "intent": 0.41,
        "brandRecall": 0.68,
        "productRecall": 0.65,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/565c74638733493c26dd46fa9ba4a13a/?p=ImM-Ou2sVMuc_NbW6T6tfA"
    },
    {
      "id": 60,
      "name": "Алиса 15 сек Фото",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Алиса AI",
      "campaign": "Запуск 28.10",
      "base": 234,
      "format": "15 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.67,
        "clarity": 0.71,
        "relevance": 0.72,
        "uniqueness": 0.71,
        "brandRecognition": 0.48,
        "brandFit": 0.79,
        "brandAttitude": 0.65,
        "intent": 0.47,
        "brandRecall": 0.66,
        "productRecall": 0.66,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/343266bab24a59b4be87daa106b374be/?p=KJtvIb_tVPX2L78wW5ammA"
    },
    {
      "id": 61,
      "name": "Алиса 15 сек теннис",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Алиса AI",
      "campaign": "Запуск 28.10",
      "base": 231,
      "format": "15 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.76,
        "like": 0.58,
        "clarity": 0.65,
        "relevance": 0.72,
        "uniqueness": 0.62,
        "brandRecognition": 0.52,
        "brandFit": 0.71,
        "brandAttitude": 0.61,
        "intent": 0.42,
        "brandRecall": 0.63,
        "productRecall": 0.64,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/231758b346743a42e0a17371133a1093/?p=TnvsH-MPGh9H6-TKx9SYiA"
    },
    {
      "id": 62,
      "name": "Алиса 15 сек учеба",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Алиса AI",
      "campaign": "Запуск 28.10",
      "base": 240,
      "format": "15 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.77,
        "like": 0.57,
        "clarity": 0.78,
        "relevance": 0.68,
        "uniqueness": 0.61,
        "brandRecognition": 0.52,
        "brandFit": 0.82,
        "brandAttitude": 0.6,
        "intent": 0.45,
        "brandRecall": 0.62,
        "productRecall": 0.71,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/bbbc0ae3270f9100381c102b0dbd1937/?p=5DXsRCImieQvJEgixqYD_w"
    },
    {
      "id": 63,
      "name": "Chad AI",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "Chad AI",
      "campaign": "Запуск 28.10",
      "base": 230,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.73,
        "like": 0.53,
        "clarity": 0.62,
        "relevance": 0.67,
        "uniqueness": 0.62,
        "brandRecognition": 0.29,
        "brandFit": 0.61,
        "brandAttitude": 0.55,
        "intent": 0.36,
        "brandRecall": 0.1,
        "productRecall": 0.1,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/16eae9e9bc2892bc0ee11fdf56772be3/?p=skYDH7uR2tY-kxGGMqnIHg"
    },
    {
      "id": 64,
      "name": "телек сбера 20 сек",
      "task": "MR-4272",
      "period": "нояб.25",
      "product": "GigaChat",
      "campaign": "Запуск 28.10",
      "base": 233,
      "format": "20 сек",
      "productionType": "Стандарт",
      "metrics": {
        "interesting": 0.69,
        "like": 0.52,
        "clarity": 0.64,
        "relevance": 0.62,
        "uniqueness": 0.55,
        "brandRecognition": 0.35,
        "brandFit": 0.61,
        "brandAttitude": 0.53,
        "intent": 0.28,
        "brandRecall": 0.75,
        "productRecall": 0.46,
        "correctFeatures": null,
        "incorrectFeatures": null
      },
      "rutubeUrl": "https://rutube.ru/video/private/29fcf2d7a44c615225087c89429efea2/?p=ZI57vYqyXz5sunP9KlagTQ"
    },
    {
      "id": 65,
      "name": "пак с актером",
      "task": "MR-4193",
      "period": "окт.25",
      "product": "Яндекс с Алисой",
      "campaign": "претест с актером",
      "base": 582,
      "format": "Ролик",
      "productionType": "Продакшн",
      "metrics": {
        "interesting": 0.71,
        "like": 0.55,
        "clarity": 0.55,
        "relevance": 0.64,
        "uniqueness": 0.59,
        "brandRecognition": 0.56,
        "brandFit": 0.71,
        "brandAttitude": 0.55,
        "intent": 0.41,
        "brandRecall": 0.85,
        "productRecall": 0.23,
        "correctFeatures": 0.26,
        "incorrectFeatures": 0.74
      },
      "rutubeUrl": "https://rutube.ru/video/private/46ed5890319ee85f29b48394057e5a85/?p=aXnKlYjSe0sKXwlPHWEbxg"
    },
    {
      "id": 66,
      "name": "пак с ИИ",
      "task": "MR-4193",
      "period": "окт.25",
      "product": "Яндекс с Алисой",
      "campaign": "претест с ИИ",
      "base": 582,
      "format": "Ролик",
      "productionType": "ИИ",
      "metrics": {
        "interesting": 0.69,
        "like": 0.55,
        "clarity": 0.53,
        "relevance": 0.62,
        "uniqueness": 0.62,
        "brandRecognition": 0.5,
        "brandFit": 0.69,
        "brandAttitude": 0.52,
        "intent": 0.35,
        "brandRecall": 0.8,
        "productRecall": 0.33,
        "correctFeatures": 0.31,
        "incorrectFeatures": 0.69
      },
      "rutubeUrl": "https://rutube.ru/video/private/fc5b06da92c99aaaf9806892945c0927/?p=Aaf6ybwAvq-SndoEr6tgEg"
    }
  ],
  "averages": {
    "interesting": 0.7156547885,
    "like": 0.5591538132,
    "clarity": 0.6322579105,
    "relevance": 0.6664027678,
    "uniqueness": 0.6089181249,
    "brandRecognition": 0.4745601536,
    "brandFit": 0.6867441752,
    "brandAttitude": 0.5581499326,
    "intent": 0.3938185965,
    "brandRecall": 0.7099308872,
    "productRecall": 0.5701459166,
    "correctFeatures": 0.5443428401,
    "incorrectFeatures": 0.2369676304
  },
  "periods": [
    "янв.21",
    "фев.24",
    "окт.24",
    "фев.25",
    "май.25",
    "июн.25",
    "июл.25",
    "авг.25",
    "окт.25",
    "нояб.25"
  ],
  "metricLabels": {
    "interesting": "Интересно (топ-2)",
    "like": "Нравится (топ-2)",
    "clarity": "Понятность (топ-1)",
    "relevance": "Актуальность (топ-2)",
    "uniqueness": "Уникальность (топ-2)",
    "brandRecognition": "Узнаваемость бренда (топ-2)",
    "brandFit": "Соответствие бренду (топ-2)",
    "brandAttitude": "Отношение к бренду ↑ (топ-2)",
    "intent": "Захотелось воспользоваться (топ-1)",
    "brandRecall": "Верно назвали бренд",
    "productRecall": "Верно назвали продукт",
    "correctFeatures": "Функции — правильный ответ",
    "incorrectFeatures": "Функции — НЕправильный ответ"
  }
};
